set_property SRC_FILE_INFO {cfile:C:/Users/dianhsu/Desktop/FPGA/edt_tutorial/edt_tutorial.srcs/constrs_1/new/GPIO_Constraints.xdc rfile:../../../edt_tutorial.srcs/constrs_1/new/GPIO_Constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N15 [get_ports {btns_5bits_tri_i[0]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R18 [get_ports {GPIO_0_0_tri_io[0]}]
